import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

const read = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");

test("IndexedDB v5 has indexed refinement hydration and isolated credential/capture stores", () => {
  const source = read("src/utils/db.ts");
  assert.match(source, /openDB\("spicylyrics", 5/);
  assert.match(source, /AIRefinements: "aiRefinements"/);
  assert.match(source, /AICredentials: "aiCredentials"/);
  assert.match(source, /AICaptures: "aiCaptures"/);
  assert.match(source, /createIndex\("byTrackConfig", \["trackUri", "configId"\]\)/);
  assert.match(source, /createIndex\("byLastAccessedAt", "lastAccessedAt"\)/);
  assert.match(source, /createIndex\("byTrack", "trackUri"\)/);
  assert.match(source, /createIndex\("byUpdatedAt", "updatedAt"\)/);
  assert.match(source, /createIndex\("byTrackUri", "trackUri"\)/);
  const cache = read("src/utils/Lyrics/AIRefinement/IndexedDBCache.ts");
  assert.match(cache, /getAllFromIndex\(ObjectStores\.AIRefinements, "byTrack", trackUri\)/);
  assert.match(cache, /queueMicrotask/);
  assert.doesNotMatch(cache.match(/async listByTrack[\s\S]*?\n  \}/)?.[0] ?? "", /\.getAll\(ObjectStores\.AIRefinements\)/);
});

test("credential UI edits in plaintext, confirms with a partial mask, and keeps provider keys separate", () => {
  const ui = read("src/components/ReactComponents/SettingsPanel/AIRefinementSettings.tsx");
  const credentials = read("src/utils/Lyrics/AIRefinement/Credentials.ts");
  assert.match(ui, /type="text"/);
  assert.match(ui, /slice\(0, 4\).*slice\(-4\)/s);
  assert.match(ui, /sl-ai-saved-key/);
  assert.match(ui, /autoComplete="off"/);
  assert.match(ui, /autoCorrect="off"/);
  assert.match(ui, /autoCapitalize="off"/);
  assert.match(ui, /spellCheck=\{false\}/);
  assert.match(ui, />Save<|>Save<\/button>/);
  assert.match(ui, /Test connection/);
  assert.match(ui, />Edit<\/button>/);
  assert.match(ui, /Delete/);
  assert.match(credentials, /utf8Bytes\(secret\) > 512/);
  assert.match(credentials, /providerId !== "gemini" && providerId !== "openai"/);
  assert.match(credentials, /ObjectStores\.AICredentials, providerId/);
  assert.match(ui, /OpenAI-compatible/);
  assert.match(ui, /API base URL/);
  assert.doesNotMatch(ui, /Start capture|Stop capture/);
  assert.doesNotMatch(ui, /Every paid refinement is saved locally/);
  assert.match(ui, /Save Current/);
  assert.match(ui, /Save All/);
  assert.match(ui, /downloadAllProviderCaptures/);
  assert.match(ui, /Choose where to save/);
  assert.match(read("src/utils/Lyrics/AIRefinement/DebugCapture.ts"), /showSaveFilePicker/);
  assert.match(ui, /View Comparison/);
  assert.match(ui, /Saved Comparison/);
  assert.match(ui, /listProviderCaptures/);
  assert.match(ui, /selectProviderCapture/);
  assert.match(ui, />Delete<\/button>/);
  assert.match(ui, /Delete All/);
  assert.match(ui, /trackLabel \?\? item\.trackUri/);
  assert.match(ui, /item\.model/);
  assert.match(ui, /item\.attempts/);
  assert.match(ui, />Original</);
  assert.match(ui, /Machine output/);
  assert.match(ui, /AI output \{attempt\.number\}/);
  assert.match(ui, /attempt\.accepted/);
  assert.match(ui, /System prompt/);
  assert.match(ui, /AI Instructions/);
  assert.match(ui, /Best-effort, text-only guidance/);
  assert.equal((ui.match(/label="AI Instructions"/g) ?? []).length, 1);
  assert.doesNotMatch(ui, /Meaning Instructions|Sound Instructions|AI_MAX_STEERING_BYTES|instructionsByteCount|steeringByteCount|soundByteCount/);
  assert.match(ui, /mixed-language phrasing/);
  const stores = read("src/utils/stores.ts");
  assert.match(stores, /persistAtom<string>\("aiInstructions"/);
  assert.match(stores, /persistAtom<string>\("aiRefinementPresets"/);
  assert.match(stores, /persistAtom<string>\("aiDefaultRefinementPreset"/);
  assert.match(stores, /persistAtom<string>\("aiSoundRefinementPresets"/);
  assert.match(stores, /persistAtom<string>\("aiDefaultSoundRefinementPreset"/);
  assert.match(stores, /_settings\.aiSteeringInstructions/);
  assert.match(stores, /_settings\.soundSteeringInstructions/);
  const page = read("src/components/Pages/PageView.ts");
  const app = read("src/app.tsx");
  assert.match(page, /contextmenu/);
  assert.match(page, /openAIRefinementComposer/);
  assert.match(page, /openAIOutputReviewPanel/);
  assert.match(page, /loadLayerComparisonRows/);
  assert.match(page, /requireBaselineMatch: baselineDocument\.DetectedChinese === true/);
  assert.match(page, /\$koreanDisplayMode\.listen\(queueProcessingSettingsRefresh\)/);
  assert.equal((page.match(/spicy-lyrics:processing-ready/g) ?? []).length, 1);
  assert.equal((app.match(/spicy-lyrics:processing-ready/g) ?? []).length, 0);
  assert.match(page, /sequence <= latestProcessingReadySequence/);
  assert.match(page, /state\.status === "failed".*toast\.error/s);
  const fetchSource = read("src/utils/Lyrics/fetchLyrics.ts");
  assert.match(fetchSource, /acceptBaseline\(uri, processedLyrics, "final", snapshot, true\)/);
  assert.doesNotMatch(fetchSource, /return \[processedLyrics, 200\]/);
  assert.doesNotMatch(fetchSource, /return \[\{ \.\.\.lyricsFromCache/);
  const singleton = read("src/utils/Lyrics/AIRefinement/singleton.ts");
  assert.match(singleton, /AI_CACHE_HYDRATION_DEADLINE_MS = 60/);
  assert.match(singleton, /composer\.publishDeferred\(trackUri, revision\)/);
  assert.match(page, /hasAIOutput/);
  assert.match(page, /if \(!hasAIOutput\).*openAIComposer\(trackUri, layer\)/s);
  assert.doesNotMatch(page, /id="AIRefinementToggle"/);
  assert.match(page, /\$meaningVisible\.set/);
  assert.doesNotMatch(page, /setTranslationEnabled\(!translationEnabled\)/);
  const translationClick = page.match(/translationToggle\.addEventListener\("click", \(\) => \{([\s\S]*?)\n\s*\}\);/)?.[1] ?? "";
  assert.match(translationClick, /\$meaningVisible\.set/);
  assert.match(translationClick, /runDefaultAI/);
  const translationContextMenu = page.match(/translationToggle\.addEventListener\("contextmenu",[\s\S]*?\n\s*\}\);/)?.[0] ?? "";
  assert.match(translationContextMenu, /preventDefault/);
  assert.match(translationContextMenu, /openAILanePanel/);
  const reviewPanel = read("src/utils/openAIOutputReviewPanel.tsx");
  assert.match(reviewPanel, /AI Pronunciation/);
  assert.match(reviewPanel, /AI Translation/);
  assert.match(reviewPanel, />Preset</);
  assert.match(reviewPanel, />Model</);
  assert.doesNotMatch(reviewPanel, /Current authority/);
  assert.match(reviewPanel, />Original</);
  assert.match(reviewPanel, /Built-in \/ Google/);
  assert.match(reviewPanel, /AI output \{attempt\.number\}/);
  assert.match(reviewPanel, /Refine again/);
  assert.match(reviewPanel, /Process with AI/);
  assert.match(reviewPanel, /Restore \{baselineLabel\}/);
  assert.match(read("src/css/Lyrics/main.css"), /MeaningHidden.*translated-below/s);
  assert.match(read("src/css/Lyrics/main.css"), /romanized-below\.romanization-static/);
  assert.match(read("src/utils/Lyrics/ProcessLyrics.ts"), /RomanizationSource = "google"/);
  assert.match(readFileSync(new URL("../src/utils/openAISteeringEditor.tsx", import.meta.url), "utf8"), /Best-effort and text-only/);
  assert.match(page, /getDefaultAIRefinementRequest/);
  assert.match(page, /AIRefined/);
  assert.match(page, /aiFeaturesEnabled/);
  assert.match(page, /refineOutput/);
  assert.doesNotMatch(page, /request\.meaning|request\.sound/);
  assert.match(page, /initialLayer === "meaning"/);
  assert.match(page, /romanizationToggle\.addEventListener\("contextmenu"/);
  const composer = read("src/utils/openAISteeringEditor.tsx");
  assert.match(composer, /Use for single click/);
  assert.match(composer, /Save preset/);
  assert.match(composer, /Delete preset/);
  assert.match(composer, /AI Translation/);
  assert.match(composer, /AI Pronunciation/);
  assert.match(composer, /Pronunciation steering/);
  assert.match(composer, /\$aiSoundRefinementPresets/);
  assert.match(composer, /Restore translation/);
  assert.match(composer, /Restore pronunciation/);
  assert.match(composer, /availableModels/);
  assert.doesNotMatch(composer, /type="checkbox"|availableOutputCount|sl-ai-fixed-output/);
  assert.match(composer, /isLarge: true/);
  assert.match(composer, /modalId: "ai-refinement"/);
  assert.match(composer, /PopupModal\.transition/);
  const defaultCss = read("src/css/default.css");
  assert.match(defaultCss, /ViewControl\.AIRefined/);
  assert.match(defaultCss, /#1ed760/);
  const settingsCss = read("src/css/settings-panel.css");
  assert.match(settingsCss, /sl-modal-container-large:has\(\.sl-ai-request-composer\)/);
  assert.match(settingsCss, /select option \{ background: #fff; color: #111; \}/);
  assert.match(settingsCss, /flex-wrap: wrap/);
  const lyricsUi = read("src/components/ReactComponents/SettingsPanel/LyricsSection.tsx");
  assert.match(lyricsUi, /Google Transliteration Fallback/);
  assert.match(lyricsUi, /Lyrics are sent to Google when needed/);
  assert.match(lyricsUi, /Target Orthography/);
  assert.doesNotMatch(lyricsUi, /Translation Backend|Sound Backend|AI automatic/);
  assert.match(ui, /Enable AI features/);
  assert.match(ui, /Always use AI/);
  assert.match(ui, /Generate AI output, then toggle/);
  assert.match(ui, /Toggle display only/);
  assert.match(ui, /Use existing pronunciation as AI baseline/);
  assert.match(ui, /raw lyrics only/);
  assert.match(singleton, /enabled && \$meaningBackend/);
  assert.doesNotMatch(read("src/utils/Lyrics/Fork/Translation.ts"), /\$meaningBackend\.get\(\) === "ai_auto"/);
  assert.match(read("src/utils/openLyricsSourcePicker.tsx"), /SelectionDiagnostics/);
  assert.match(read("src/utils/openLyricsSourcePicker.tsx"), /current\?\.uri === trackUri/);
  assert.match(read("src/utils/openLyricsSourcePicker.tsx"), /selectionScore/);
  assert.match(ui, /Saved AI Results/);
  assert.match(ui, /downloadRefinementCacheRecord/);
  assert.match(ui, /probeControllerRef/);
  assert.match(ui, /configuration_changed/);
  assert.match(ui, /notifyAIRefinementCredentialChanged/);
  assert.match(ui, /HTTPS required/);
  assert.match(ui, /loadProviderCredential\(providerId\)/);
  const changeHandler = ui.match(/onChange=\{\(event\) => setDraft\(event\.currentTarget\.value\)\}/g) ?? [];
  assert.equal(changeHandler.length, 1);
  assert.doesNotMatch(ui, /onChange=.*saveProviderCredential/);
});

test("AI features are a first-class settings section, not hidden in Experiments", () => {
  const panel = read("src/components/ReactComponents/SettingsPanel/ExperimentsPanel.tsx");
  const settings = read("src/components/ReactComponents/SettingsPanel/index.tsx");
  const experiments = read("src/utils/experiments.ts");
  assert.doesNotMatch(panel, /AIRefinementSettings/);
  assert.doesNotMatch(experiments, /aiRefinement/);
  assert.match(settings, /AITranslationSection/);
  assert.match(settings, /"AI Features"/);
});

test("key storage and cache clearing remain separated from normal settings and credentials", () => {
  const credentials = read("src/utils/Lyrics/AIRefinement/Credentials.ts");
  const cacheTools = read("src/utils/LyricsCacheTools.ts");
  assert.doesNotMatch(credentials, /LocalStorage|SL:settings|SL:uiState/);
  assert.match(credentials, /ObjectStores\.AICredentials/);
  assert.match(cacheTools, /clearAllAIRefinements/);
  assert.doesNotMatch(cacheTools, /deleteGeminiCredential|AICredentials/);
});
