import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

const read = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");

test("IndexedDB v4 has isolated refinement, credential, and durable capture stores", () => {
  const source = read("src/utils/db.ts");
  assert.match(source, /openDB\("spicylyrics", 4/);
  assert.match(source, /AIRefinements: "aiRefinements"/);
  assert.match(source, /AICredentials: "aiCredentials"/);
  assert.match(source, /AICaptures: "aiCaptures"/);
  assert.match(source, /createIndex\("byTrackConfig", \["trackUri", "configId"\]\)/);
  assert.match(source, /createIndex\("byLastAccessedAt", "lastAccessedAt"\)/);
  assert.match(source, /createIndex\("byUpdatedAt", "updatedAt"\)/);
  assert.match(source, /createIndex\("byTrackUri", "trackUri"\)/);
});

test("credential UI edits in plaintext, confirms with a partial mask, and keeps provider keys separate", () => {
  const ui = read("src/components/ReactComponents/SettingsPanel/AIRefinementSettings.tsx");
  const credentials = read("src/utils/Lyrics/AIRefinement/Credentials.ts");
  assert.match(ui, /type="text"/);
  assert.match(ui, /slice\(0, 4\).*slice\(-4\)/s);
  assert.match(ui, /sl-ai-saved-key/);
  assert.match(ui, /autoComplete="off"/);
  assert.match(ui, /autoCorrect="off"/);
  assert.match(ui, /autoCapitalize="off"/);
  assert.match(ui, /spellCheck=\{false\}/);
  assert.match(ui, />Save<|>Save<\/button>/);
  assert.match(ui, /Test connection/);
  assert.match(ui, />Edit<\/button>/);
  assert.match(ui, /Delete/);
  assert.match(credentials, /utf8Bytes\(secret\) > 512/);
  assert.match(credentials, /providerId !== "gemini" && providerId !== "openai"/);
  assert.match(credentials, /ObjectStores\.AICredentials, providerId/);
  assert.match(ui, /OpenAI-compatible/);
  assert.match(ui, /API base URL/);
  assert.doesNotMatch(ui, /Start capture|Stop capture/);
  assert.doesNotMatch(ui, /Every paid refinement is saved locally/);
  assert.match(ui, /Save Current/);
  assert.match(ui, /Save All/);
  assert.match(ui, /downloadAllProviderCaptures/);
  assert.match(ui, /Choose where to save/);
  assert.match(read("src/utils/Lyrics/AIRefinement/DebugCapture.ts"), /showSaveFilePicker/);
  assert.match(ui, /View Comparison/);
  assert.match(ui, /Saved Comparison/);
  assert.match(ui, /listProviderCaptures/);
  assert.match(ui, /selectProviderCapture/);
  assert.match(ui, />Delete<\/button>/);
  assert.match(ui, /Delete All/);
  assert.match(ui, /trackLabel \?\? item\.trackUri/);
  assert.match(ui, /item\.model/);
  assert.match(ui, /item\.attempts/);
  assert.match(ui, /Before AI/);
  assert.match(ui, /AI output/);
  assert.match(ui, /System prompt/);
  assert.match(ui, /AI Instructions/);
  assert.equal((ui.match(/label="AI Instructions"/g) ?? []).length, 1);
  assert.doesNotMatch(ui, /Meaning Instructions|Sound Instructions|AI_MAX_STEERING_BYTES|instructionsByteCount|steeringByteCount|soundByteCount/);
  assert.match(ui, /mixed-language phrasing/);
  const stores = read("src/utils/stores.ts");
  assert.match(stores, /persistAtom<string>\("aiInstructions"/);
  assert.match(stores, /persistAtom<string>\("aiRefinementPresets"/);
  assert.match(stores, /persistAtom<string>\("aiDefaultRefinementPreset"/);
  assert.match(stores, /_settings\.aiSteeringInstructions/);
  assert.match(stores, /_settings\.soundSteeringInstructions/);
  const page = read("src/components/Pages/PageView.ts");
  assert.match(page, /contextmenu/);
  assert.match(page, /openAIRefinementComposer/);
  assert.match(page, /getDefaultAIRefinementRequest/);
  assert.match(page, /AIRefined/);
  assert.match(page, /refineOutput/);
  assert.match(page, /request\.meaning && request\.sound/);
  assert.match(page, /aiRefinementCoordinator\.subscribe/);
  const composer = read("src/utils/openAISteeringEditor.tsx");
  assert.match(composer, /Use for single click/);
  assert.match(composer, /Save preset/);
  assert.match(composer, /Delete preset/);
  assert.match(composer, /Translation/);
  assert.match(composer, /Pronunciation \/ transliteration/);
  assert.match(composer, /Restore translation/);
  assert.match(composer, /Restore pronunciation/);
  assert.match(composer, /availableModels/);
  assert.match(composer, /type="checkbox"/);
  assert.match(composer, /isLarge: true/);
  const defaultCss = read("src/css/default.css");
  assert.match(defaultCss, /ViewControl\.AIRefined/);
  assert.match(defaultCss, /#1ed760/);
  const settingsCss = read("src/css/settings-panel.css");
  assert.match(settingsCss, /sl-modal-container-large:has\(\.sl-ai-request-composer\)/);
  assert.match(settingsCss, /select option \{ background: #fff; color: #111; \}/);
  assert.match(settingsCss, /flex-wrap: wrap/);
  const lyricsUi = read("src/components/ReactComponents/SettingsPanel/LyricsSection.tsx");
  assert.match(lyricsUi, /Translation Backend/);
  assert.match(lyricsUi, /Google Translate/);
  assert.match(lyricsUi, /AI Translate on demand/);
  assert.match(lyricsUi, /Sound Backend/);
  assert.match(lyricsUi, /Target Orthography/);
  assert.match(lyricsUi, /AI automatic/);
  assert.match(read("src/utils/Lyrics/Fork/Translation.ts"), /\$meaningBackend\.get\(\) === "ai_auto"/);
  assert.match(read("src/utils/openLyricsSourcePicker.tsx"), /SelectionDiagnostics/);
  assert.match(read("src/utils/openLyricsSourcePicker.tsx"), /current\?\.uri === trackUri/);
  assert.match(read("src/utils/openLyricsSourcePicker.tsx"), /selectionScore/);
  assert.match(ui, /Saved AI Results/);
  assert.match(ui, /downloadRefinementCacheRecord/);
  assert.match(ui, /probeControllerRef/);
  assert.match(ui, /configuration_changed/);
  assert.match(ui, /notifyAIRefinementCredentialChanged/);
  assert.match(ui, /HTTPS required/);
  assert.match(ui, /loadProviderCredential\(providerId\)/);
  const changeHandler = ui.match(/onChange=\{\(event\) => setDraft\(event\.currentTarget\.value\)\}/g) ?? [];
  assert.equal(changeHandler.length, 1);
  assert.doesNotMatch(ui, /onChange=.*saveProviderCredential/);
});

test("AI providers are a first-class settings section, not hidden in Experiments", () => {
  const panel = read("src/components/ReactComponents/SettingsPanel/ExperimentsPanel.tsx");
  const settings = read("src/components/ReactComponents/SettingsPanel/index.tsx");
  const experiments = read("src/utils/experiments.ts");
  assert.doesNotMatch(panel, /AIRefinementSettings/);
  assert.doesNotMatch(experiments, /aiRefinement/);
  assert.match(settings, /AITranslationSection/);
  assert.match(settings, /"AI providers"/);
});

test("key storage and cache clearing remain separated from normal settings and credentials", () => {
  const credentials = read("src/utils/Lyrics/AIRefinement/Credentials.ts");
  const cacheTools = read("src/utils/LyricsCacheTools.ts");
  assert.doesNotMatch(credentials, /LocalStorage|SL:settings|SL:uiState/);
  assert.match(credentials, /ObjectStores\.AICredentials/);
  assert.match(cacheTools, /clearAllAIRefinements/);
  assert.doesNotMatch(cacheTools, /deleteGeminiCredential|AICredentials/);
});
